### ISSUE TITLE
Consider adopting a functional approach to mixins

### ISSUE THREAD

**Issue by JanMiksovsky** [ComponentKitchen/core-component-mixins#1]
I’d welcome some opinions on whether we should change the form mixins take. On the [master](https://github.com/ComponentKitchen/core-component-mixins/tree/5cd455712ad07b5a5d85b49559f0bb4201bb9931) branch, mixins take the form of a class. A web component mixin like AutomaticNodeFinding in this repo has a signature like this:

```
export default class AutomaticNodeFinding {
  createdCallback() {
    // Do attribute node finding work here.
  }
}
```

Someone who wants to use this mixin class needs to invoke a separate facility, Composable, to extend a base class with this mixin:

```
let MyElement = Composable.compose.call(HTMLElement, AutomaticNodeFinding);
```

An important feature of `Composable.compose` is that _by default_ it will resolve any name conflicts between mixin members and base class members. In the example above, it turns out the base HTMLElement class doesn’t define a createdCallback method — but if it did, Composable would ensure that invoking MyElement.createdCallback invoked _both_ the base implementation and the mixin implementation above.

The main problem with this approach is that it’s somewhat magic. While the behavior of Composable is relatively easy to explain, unless one reads the complete documentation, it’s possible to be surprised by what Composable does.

In response to our recent [blog post](https://component.kitchen/blog/posts/composing-mixins-to-make-a-solid-foundation-for-web-components) about mixin classes, @justinfagnani [suggested](https://plus.google.com/+JanMiksovsky/posts/bFBBGB8kEs8) an alternative: a mixin can just be a function that takes a class argument and uses that to create and returns a new subclass:

```
export default (base) => class AutomaticNodeFinding extends base {
  createdCallback() {
    if (super.createdCallback) { super.createdCallback(); }
    // Do attribute node finding work here.
  }
};
```

The `(base) => class … extends base` signature looks slightly unusual, but just says that we’re defining a function that takes a base class and returns a new subclass of it.

With this approach, the mixin author can directly do whatever they want to the new subclass. That’s flexible, but also means they have to handle composition themselves. They have to be aware of how to design mixins, taking care to invoke base class methods/properties instead of just overriding them. In general this means: in every exposed mixin member, invoke some form of `super`.

A core advantage of this approach is that the mixin can be applied directly to a base class with simple function invocation:

```
let MyElement = AutomaticNodeFinding(HTMLElement);
```

I think there’s a great deal of merit to Justin’s suggestion. I’ve created a new branch called [functions](https://github.com/ComponentKitchen/core-component-mixins/tree/fc56589c49122c99ed6176e1eb5f6ca50d2fdd86) that explores this suggestion, and implements the core web component mixins as functions.

Aside: I’d originally pursued an approach halfway between Composable and what Justin proposes. In that earlier approach, a mixin was still a class (like with Composable), but no magic composition took place. Instead, the mixin author had to manually compose members using `super` (like Justin’s suggestion). I ran into practical problems getting this approach to work. In particular, because of how it was written, it wasn’t possible to correctly transpile an ES6 `super` call so that it worked correctly in ES5. Justin’s function solution just happens to be something a transpiler can understand so that it can compile it correctly.

Overall I like this mixin function approach quite a bit. Having played with it for a few days, I see the following pros/cons:

_Cons_
- The mixin author must remember to always manually invoke `super`. This doesn’t seem bad for a trivial mixin like the one above, which has only a single method. In practice, we have mixins with a dozen members. The Composable facility’s default composition rules make the mixin code cleaner.
- It’s easy to forget to invoke `super`. If you forget to do this, you might not see a problem immediately. The problem might only get revealed when someone tries to apply your mixin to a class of theirs with a member of the same name.
- The boilerplate code to invoke `super` isn’t always the same. I’ve written an initial draft of [conventions for extending base class methods and properties in a mixin](https://docs.google.com/document/d/1W7xAXQZCitJX2HvEhpBKflCR3mWKg_-ZxYOJ5XpkaAc/edit?usp=sharing). The rules are fairly simple, but you have to learn them. In contrast, Compostable’s default rules remove the need to remember what boilerplate to use.
- While a mixin author can write arbitrary code to handle complex composition scenarios, in practice I think most mixin authors will want to use a handful of standard composition rules. Composable’s ability to use `@decorator` syntax lets the author succinctly declare what they want to do, which I think is easier to read. A declaration that says “Use the `preferBaseResult` rule” expresses _intent_. In contrast, when I read someone else’s mixin function, I have to read the plain JavaScript, then figure out what it’s doing.
- The syntax for adding a large number of mixins looks ugly: `Mixin1(Mixin2(Mixin3(base)))` is harder to read than `base.compose(Mixin1, Mixin2, Mixin3)`. That could be addressed by preserving a `compose` helper that applies a bunch of functions. The important point is use of the helper is entirely optional. This is similar to the way Justin offers a `mix` helper in his [mixwith.js](https://github.com/justinfagnani/mixwith.js) solution.
- Composable can ensure that the same mixin isn't applied twice to the same prototype chain. A mixin function, in contrast, won't bother to do that. We could introduce a helper to do that, but then it starts to feel a little more like a framework again.

_Pros_
- It feels really good to just use functions on their own, without the need for a separate helper like Composable. This is consistent with our desire to work closer to the metal. Composable is a lightweight piece of code, barely a kernel of a framework, but it still feels a _little_ like a framework. This functional approach removes even the need for a kernel. There's no framework — just mixins.
- The intrusiveness of the `super` invocations reminds developers that composition is taking place, which is probably a good thing. The code shows exactly what’s going to happen. In the Composable mixin-as-class approach at the top, it might be easy for a developer to forget composition is going to taking place.
- When debugging, I’m finding it’s much easier to debug an explicitly composed function that uses `super` inline than to debug an anonymous, programmatically composed function that accomplishes the same result.
- Generally speaking, this approach feels less magic. While it requires the mixin author to take more care writing their mixin members, it’s likely that comparatively few people are going write these mixins — most people are just going to _use_ mixins.
- As functional programming continues to become more popular (React, Elm, virtual-dom, etc.), using higher-order functions this way will feel less strange.
- This approach feels more framework-agnostic. As such, I think there’s a greater chance that other groups could be convinced to write component mixins this way. I think this is a critical point. I'd love to be able to convince, say, the Google AMP team to share an accessibility mixin for their carousel web component. They're more likely to adopt such a mixin if it's delivered as a standalone function than if it's a class that has to be composed in with Composable.

The performance implications are unclear, possibly favoring mixin functions. The Composable master branch currently does a bunch of prototype chain inspection and manipulation at load time. On the other hand, that cost is incurred once: if a base class and mixin have a conflict, it can be resolved right then, at load time. From that point on, the individual mixin methods/properties don’t have to worry about conflicts. The mixin-as-function approach has no load time hit, but every method ends up having to inspect `super` for the presence of the method or property in question. They have to do this every time they’re called, even though the answer for a given mixin+base combination will never change. Depending on the app, the cost of that self-inspection might add up.

On balance, I'm leaning towards adopting this functional approach.

@robbear, @goldoraf: What do you think?

**Comment by JanMiksovsky** [comment]
I forgot to mention: if we like mixins as functions, but also like the ability to provide default composition rules, composition could be offered as a separate, optional feature. This would probably take the form of a function that's applied to a class to resolve any conflicts its members has with its base class(es):

    function MyMixin(base) {
      return Composable.applyCompositionRules(class MyMixin extends base {
        method() {
          // No need to invoke super here, because this will get composed with base method.
        }
      });
    }

**Comment by justinfagnani** [comment]
Another option is to decorate the mixin function so that it tries to call super. I've experimented with this as part of mixwith.js.

```javascript
const MyMixin = ComposableMixin((superclass) => class extends superclass {
  createdCallback() {
    this.doSomething();
  }
});
```

Then the user of the mixin doesn't have to do anything different.

What `ComposableMixin` does is take the return value of the mixin application and replace any own methods with wrappers that call super then invoke the mixin method.

There are so many pitfalls here though. Super calls may take arguments and return values, and how to deal with these is complicated. You can introspect the mixin methods, assume that if there's a super it has the same signature, and build that super call. Return values... can't do much reasonable there. Then there's ordering. Does the super call need to come before, after or in the middle of the mixin method?

Thus... why I prefer explicit super calls in mixins.

**Comment by robbear** [comment]
Here is how I look at the issue:
1. What form of mixin approach is most likely to be adopted by as wide a range of contributors as possible so that...
2. npm becomes a great model for discoverability and distribution of atomic pieces for web component construction and that...
3. The model is close enough to the metal so that independent and entirely optional support libraries can flourish and output the agreed-upon, sharable form of mixin.

Under these requirements, it seems like the functional approach is best suited, despite the boilerplate advantages of the class-based Composable approach. The discussion should continue, I think, as to how optional support libraries may ease issues such as super calls and other repetitious patterns that will show up so close to the metal.

Introducing a required support class at the beginning of the discussion of mixin architecture is an obvious disadvantage. The functional approach seems more promising in that manner.

**Comment by JanMiksovsky** [comment]
Thank you @justinfagnani and @robbear for your comments.

Based on your endorsement, and on another couple of days using this functional approach, I think we should go ahead and switch to it. I was able to quickly port a large number of mixin classes to mixin functions, with positive results.

* Although the mixins now need to invoke `super` manually, this doesn't feel that bad in practice.
* Being able to avoid the use of a framework feels like a huge improvement.
* The new mixin functions are significantly easier to debug, because there are no longer anonymous functions to step through.

One minor downside is that some of the components I'm writing used a dozen mixins, and applying all of those as function calls looks ugly. To solve that, I've converted Composable itself from a class to a mixin, and added it to this core-component-mixins repo. This just adds a `compose` function that can apply a list of mixins. This sugar preserves the brevity that was possible with the previous Composable class' `compose` function. However, use of the Composable *mixin* is now entirely optional. It's just sugar.

Given how promising this is, I'm going to go ahead and merge the new function approach into the master branch.

@goldoraf: This will be a breaking change for your initial Bosonic [experiment](https://github.com/bosonic-labs/composable-experiment), but your code will not need to change much. You can drop the dependency on ComponentKitchen/composable, since that's no longer necessary. You' can import the Composable helper from core-component-mixins/src instead. The syntax used to create your Bosonic base class will change very slightly; see the updated X-Tag example for reference.

**Comment by JanMiksovsky** [comment]
This is now on master.

**Comment by justinfagnani** [comment]
Aweomse @JanMiksovsky :)

Given that the desire to have a nice syntax to apply mixins is the main reason behind [mixwith.js][https://github.com/justinfagnani/mixwith.js/commits?author=justinfagnani], I wonder if you'd be open to using that?

**Comment by JanMiksovsky** [comment]
@justinfagnani Yes, I'd be open to that. The Composable mixin and mixwith are slightly different in intent and syntax, so we'd have to resolve those differences. I'm going to be traveling for the next 2.5 weeks, but will give this some thought. I'll follow up when I'm back at home.

**Comment by justinfagnani** [comment]
Sounds good. I'll be away as well, so maybe we can set up a chat in 2016. Cheers!
